# Generated by Django 4.0.6 on 2022-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_career_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='short_desription',
        ),
        migrations.AddField(
            model_name='about',
            name='excerpt',
            field=models.CharField(default='', max_length=150, verbose_name='Excerpt'),
        ),
    ]
