# Generated by Django 4.0.6 on 2022-08-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_about_short_desription_about_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.RemoveField(
            model_name='programmingskills',
            name='name',
        ),
        migrations.AddField(
            model_name='programmingskills',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='career',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='career',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Starts From Date'),
        ),
    ]
