# Generated by Django 4.0.6 on 2022-08-29 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_about_options_remove_programmingskills_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='end',
            field=models.DateField(default=datetime.date.today, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='career',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Starts From Date'),
        ),
    ]
