# Generated by Django 4.0.6 on 2023-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_works_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
