# Generated by Django 4.0.6 on 2023-07-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedbacks',
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
